### ISSUE TITLE
from pysettings import conf

### ISSUE THREAD

**Issue by ashishaware28** [UmSenhorQualquer/pyforms#38] opened 2016-12-19 06:46 UTC
While run first program of pyforms i was getting pysettings error. After that i had installed pysettings module but still this error is coming conf is **ImportError: cannot import name conf**
PLease provide better solution

**Comment by JBauto** [comment] 2016-12-19 08:56
Hi,
Did you install pyforms and pysettings from pip? They aren't updated to the latest version and you should install using the main repos.
- pip install git+https://github.com/UmSenhorQualquer/pyforms.git --upgrade
- pip install git+https://github.com/UmSenhorQualquer/pysettings.git --upgrade

(Duplicate of #37)

**Comment by ashishaware28** [comment] 2016-12-28 13:59
thank you sir

**Closed** 2016-12-29 14:46 UTC

**Comment by williamhatcher** [comment] 2017-10-30 15:06
Please note this in the documentation.
